# 用做API接口使用
# 含编译环境（用于本地编译使用）
# 
# docker pull ibbd/java-python3-server-cytyon
#
# Version 2017-04-18

FROM ibbd/java-python3-server

MAINTAINER Alex Cai cyy0523xc@gmail.com

RUN \
    apt-get update \
    && apt-get install -y build-essential \
    && pip3 install cython \

