# 用做API接口使用
# docker pull ibbd/java-python3-server
#
# Version 2017-04-18

FROM ibbd/java-python3

MAINTAINER Alex Cai cyy0523xc@gmail.com

RUN \
    pip install flask \
        flask_restful \
        pyyaml

